timeout = 30000
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[privacy]


[privacy.twitter]
disabled = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true